### ISSUE TITLE
Error when compile mods

### ISSUE THREAD

**Issue by Memoraike** [Konijima/pzpw-compiler#19]
Hi! First very very very mush thanks for this awesome tool!
I got error when try compile my mod
trace: 
```
TypeError: Cannot read properties of undefined (reading 'fileName')
    at file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/transpiler.js:61:133
    at Array.forEach (<anonymous>)
    at file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/transpiler.js:58:28
    at new Promise (<anonymous>)
    at transpile (file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/transpiler.js:52:12)
    at ModsCompiler (file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/compilers/mods-compiler.js:99:35)
    at Compiler.compileMods (file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/compiler.js:97:15)
    at async Compiler.exec (file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/compiler.js:66:13)
    at async Compiler.run (file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/lib/compiler.js:24:9)
    at async file:///home/meow/.volta/tools/image/node/16.18.0/lib/node_modules/pzpw-compiler/dist/index.js:29:9

PZPW Compiler terminated! (2.347s)
```

**Comment by Konijima** [comment]
Will close this issue now that https://github.com/Konijima/pzpw-compiler/pull/20 has been merged.
